[package]
name = "backends-common"
edition = "2024"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
spexus-lang = { path = "./../../spexus-lang" }